import sys
import argparse
import tempfile
import os

from pvactools.tools.pvacseq.generate_protein_fasta import run_generate_protein_fasta

def define_parser():
    parser = argparse.ArgumentParser(
        "pvacvector create_vector_ordering_form",
        description="Generate a colored version of the final vector design",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )
    parser.add_argument(
        "input_vcf",
        help="A VEP-annotated single- or multi-sample VCF containing genotype, transcript, "
            +"Wildtype protein sequence, and Frameshift protein sequence information."
            +"The VCF may be gzipped (requires tabix index)."
    )
    parser.add_argument(
        "input_tsv",
        help = "A pVACseq all_epitopes, filtered, or aggregated TSV file with epitopes to use for subsetting the input VCF to peptides of interest. Only the peptide sequences for the epitopes in the TSV will be used when creating the FASTA."
    )
    parser.add_argument(
        "input_fasta",
        help="A pVACvector output fasta file. This is where the formatting will be applied."
    )
    parser.add_argument(
        'classI_tsv',
        help='The path to the classI all_epitopes.aggregated.tsv'
    )
    parser.add_argument(
        'classII_tsv',
        help='The path to the classII all_epitopes.aggregated.tsv'
    )
    parser.add_argument(
        "output_file",
        help="The prefix for the output files' names"
    )
    parser.add_argument(
        "sample_name",
        help="The name of the sample being processed. Must be a sample ID in the input VCF #CHROM header line."
    )
    parser.add_argument(
        "-o", "--output-path",
        help="The path where the output file will be generated."
    )
    parser.add_argument(
        "-p", "--phased-proximal-variants-vcf",
        help="A VCF with phased proximal variant information to incorporate into the predicted fasta sequences. Must be gzipped and tabix indexed."
    )
    parser.add_argument(
        '--pass-only',
        help="Only process VCF entries with a PASS status.",
        default=False,
        action='store_true',
    )
    parser.add_argument(
        "--biotypes", type=lambda s:[a for a in s.split(',')],
        help="A list of biotypes to use for pre-filtering transcripts for processing in the pipeline.",
        default=['protein_coding']
    )
    parser.add_argument(
        "-d", "--downstream-sequence-length",
        default="1000",
        help="Cap to limit the downstream sequence length for frameshifts when creating the fasta file. "
            + "Use 'full' to include the full downstream sequence."
    )
    parser.add_argument(
        '--include-review-candidates',
        help="Include the processing of candidates marked for review.",
        default=False,
        action='store_true'
    )
    parser.add_argument(
        '--variants',
        help='The path to the variants.final.annotated.tsv file generated by the pipeline'
    )
    parser.add_argument(
        '--all-epitopes',
        help='If you want to generate 51mer for all epitopes',
        default=False,
        action='store_true'
    )
    parser.add_argument(
        '--classI-IC50',
        help='Maximum classI IC50 score to annotate',
        default=1000,
        type=float
    )
    parser.add_argument(
        '--classI-percent',
        help='Maximum classI percentile to annotate',
        default=2,
        type=float
    )
    parser.add_argument(
        '--classII-IC50',
        help='Maximum classII IC50 score to annotate',
        default=500,
        type=float
    )
    parser.add_argument(
        '--classII-percent',
        help='Maximum classII percentile to annotate',
        default=2,
        type=float
    )
    parser.add_argument(
        '--prob-pos',
        nargs='*', 
        help='Problematic position to make large',
        default=''
    )
    return parser


def main(args_input = sys.argv[1:]):
    parser = define_parser()
    args = parser.parse_args(args_input)
    flanking_sequence_length = 25

    tmpdir = tempfile.mkdtemp()

    run_generate_protein_fasta(
        input_vcf=args.input_vcf,
        flanking_sequence_length=flanking_sequence_length,
        output_file=os.path.join(tmpdir.name, args.output_file),
        input_tsv=args.input_tsv,
        phased_proximal_variants_vcf=args.phased_proximal_variants_vcf,
        pass_only=args.pass_only,
        biotypes=args.biotypes,
        mutant_only=True,
        aggregate_report_evaluation=['Accept', 'Review'] if args.include_review_candidates else ['Accept'],
        downstream_sequence_length=args.downstream_sequence_length,
        sample_name=args.sample_name,
        peptide_ordering_form=True
    )

    file_path = os.path.join(args.output_path, args.output_file)
    file_prefix = os.path.join(args.output_path, f"{args.output_file}_{args.sample_name}")


if __name__ == "__main__":
    main()